metadata:
  name: "Check that databases are encrypted"
  id: "CUSTOM_AWS_1"
  category: "ENCRYPTION"
scope:
  provider: aws
definition:
  and:
    - cond_type: "attribute"
      resource_types: 
      - "aws_db_instance"
      attribute: "storage_encrypted"
      operator: "equals"
      value: "true"