name: CI

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Tar files
        run: tar -cf checkout.tar ./
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: checkout.tar
          path: checkout.tar

  kyverno:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2.1.0
        with:
          name: checkout.tar

      - name: Get kyverno
        run: |
          wget -O - https://github.com/kyverno/kyverno/releases/download/v1.5.4/kyverno-cli_v1.5.4_linux_x86_64.tar.gz | \
          tar -C /usr/local/bin -xzf - kyverno

      - name: Kyverno tests
        run: ./kyverno test kubernetes/kyverno

  release:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - kyverno
      - semver

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/download-artifact@v2.1.0
        with:
          name: checkout.tar
      # - uses: "marvinpinto/action-automatic-releases@v1.2.1"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: ${{ needs.semver.outputs.semantic_version}}
      #     prerelease: false
      #     title: ${{ needs.semver.outputs.semantic_version}}
      #     files: "*"


  semver:
    name: Generate a semantic version number
    runs-on: ubuntu-latest
    outputs:
      semantic_version: ${{ steps.semver.outputs.semantic_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Semver run
        id: semver
        uses: lukaszraczylo/semver-generator@1.4.2
        with:
          config_file: .github/semver.yaml
          repository_local: true